const API='/api/v1/admin';
const state={token:sessionStorage.getItem('adminToken')||'',admin:JSON.parse(sessionStorage.getItem('adminUser')||'null'),page:'dashboard',pageNo:1,categories:[],products:[],admins:[]};
const $=s=>document.querySelector(s), money=c=>`¥${(Number(c||0)/100).toFixed(2)}`, date=v=>v?new Date(v).toLocaleString('zh-CN'):'—';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const titles={dashboard:'经营概览',products:'商品管理',categories:'分类管理',orders:'订单管理',users:'用户管理',admins:'管理员账号',audit:'审计日志'};
const statusText={PENDING_PAYMENT:'待付款',PAID:'待发货',SHIPPED:'已发货',COMPLETED:'已完成',CANCELLED:'已取消'};
function toast(msg,error=false){const e=$('#toast');e.textContent=msg;e.className=`toast show${error?' error-toast':''}`;setTimeout(()=>e.className='toast',2600)}
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const res=await fetch(`${API}${path}`,{...opt,headers});let body={};try{body=await res.json()}catch{}if(res.status===401){logout();throw new Error('登录已过期，请重新登录')}if(!res.ok)throw new Error(body.message||`请求失败 (${res.status})`);return body.data}
function showApp(){if(!state.token)return showLogin();$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#adminIdentity').innerHTML=`<b>${esc(state.admin?.displayName||state.admin?.username)}</b><small>${state.admin?.role==='SUPER_ADMIN'?'超级管理员':'运营管理员'}</small>`;document.querySelectorAll('.super-only').forEach(x=>x.classList.toggle('hidden',state.admin?.role!=='SUPER_ADMIN'));navigate('dashboard')}
function showLogin(){$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')}
function logout(){sessionStorage.removeItem('adminToken');sessionStorage.removeItem('adminUser');state.token='';state.admin=null;showLogin()}
async function navigate(page){state.page=page;state.pageNo=1;$('#pageTitle').textContent=titles[page];document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#content').innerHTML='<div class="loading">正在加载数据…</div>';try{await render()}catch(e){$('#content').innerHTML=`<div class="panel empty">${esc(e.message)}</div>`;toast(e.message,true)}}
async function render(){const fn={dashboard:dashboardPage,products:productsPage,categories:categoriesPage,orders:ordersPage,users:usersPage,admins:adminsPage,audit:auditPage}[state.page];await fn()}
async function dashboardPage(){const d=await api('/dashboard');const counts=d.orderCounts||{},max=Math.max(1,...Object.values(counts));$('#content').innerHTML=`<div class="stats"><div class="stat"><small>启用商品</small><b>${d.enabledProducts}</b></div><div class="stat"><small>累计订单</small><b>${d.orders}</b></div><div class="stat"><small>商城用户</small><b>${d.users}</b></div><div class="stat"><small>成交金额</small><b>${money(d.revenueCents)}</b></div></div><div class="panel"><div class="panel-head"><h3>订单状态分布</h3><span class="badge ${d.lowStockSkus?'warn':''}">低库存 SKU：${d.lowStockSkus}</span></div><div class="order-bars">${Object.entries(statusText).map(([k,v])=>`<div class="bar-row"><span>${v}</span><div class="bar"><i style="width:${(counts[k]||0)/max*100}%"></i></div><b>${counts[k]||0}</b></div>`).join('')}</div></div>`}
async function loadCategories(){state.categories=await api('/categories');return state.categories}
async function categoriesPage(){const items=await loadCategories();$('#content').innerHTML=`<div class="panel"><div class="toolbar"><div></div><button class="primary" onclick="categoryModal()">新增分类</button></div><div class="table-wrap"><table><thead><tr><th>分类名称</th><th>排序</th><th>状态</th><th>操作</th></tr></thead><tbody>${items.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${x.sortOrder}</td><td><span class="badge ${x.enabled?'':'off'}">${x.enabled?'启用':'停用'}</span></td><td class="actions"><button onclick="editCategory('${x.id}')">编辑</button></td></tr>`).join('')}</tbody></table></div></div>`}
window.editCategory=id=>categoryModal(state.categories.find(x=>x.id===id));
window.categoryModal=function(x=null){openModal(x?'编辑分类':'新增分类',`<div class="form-grid"><label class="field">分类名称<input id="cName" value="${esc(x?.name||'')}" required></label><label class="field">排序<input id="cSort" type="number" value="${x?.sortOrder||0}"></label><label class="field">状态<select id="cEnabled"><option value="true" ${x?.enabled!==false?'selected':''}>启用</option><option value="false" ${x?.enabled===false?'selected':''}>停用</option></select></label><div class="form-actions"><button class="secondary" type="button" onclick="closeModal()">取消</button><button class="primary" type="button" onclick="saveCategory('${x?.id||''}')">保存</button></div></div>`)};
window.saveCategory=async id=>{try{const body={name:$('#cName').value.trim(),sortOrder:Number($('#cSort').value),enabled:$('#cEnabled').value==='true'};await api(id?`/categories/${id}`:'/categories',{method:id?'PATCH':'POST',body:JSON.stringify(body)});closeModal();toast('分类已保存');render()}catch(e){toast(e.message,true)}};
async function productsPage(){if(!state.categories.length)await loadCategories();const keyword=$('#productKeyword')?.value||'',d=await api(`/products?page=${state.pageNo}&pageSize=15&keyword=${encodeURIComponent(keyword)}`);state.products=d.items;$('#content').innerHTML=`<div class="panel"><div class="toolbar"><div class="filters"><input id="productKeyword" placeholder="搜索商品名称" value="${esc(keyword)}"><button class="secondary" onclick="state.pageNo=1;render()">搜索</button></div><button class="primary" onclick="productModal()">新增商品</button></div><div class="table-wrap"><table><thead><tr><th>商品</th><th>分类</th><th>价格 / 库存</th><th>销量</th><th>状态</th><th>操作</th></tr></thead><tbody>${d.items.map(x=>{const stock=x.skus.reduce((n,s)=>n+s.stock,0),min=Math.min(...x.skus.map(s=>s.priceCents));return `<tr><td><div class="product-cell"><img src="${esc(x.image)}"><div><b>${esc(x.name)}</b><div class="muted">${esc(x.subtitle)}</div></div></div></td><td>${esc(x.category)}</td><td>${money(min)}<div class="muted">${x.skus.length} SKU / 库存 ${stock}</div></td><td>${x.sales}</td><td><span class="badge ${x.enabled?'':'off'}">${x.enabled?'在售':'下架'}</span></td><td class="actions"><button onclick="editProduct('${x.id}')">编辑</button><button onclick="editSkus('${x.id}')">库存</button></td></tr>`}).join('')}</tbody></table></div>${pager(d)}</div>`}
window.editProduct=id=>productModal(state.products.find(x=>x.id===id));window.editSkus=id=>skuModal(state.products.find(x=>x.id===id));
window.productModal=function(x=null){const options=state.categories.map(c=>`<option value="${c.id}" ${x?.categoryId===c.id?'selected':''}>${esc(c.name)}</option>`).join('');openModal(x?'编辑商品':'新增商品',`<div class="form-grid"><label class="field">商品名称<input id="pName" value="${esc(x?.name||'')}" required></label><label class="field">分类<select id="pCategory">${options}</select></label><label class="field full">副标题<input id="pSubtitle" value="${esc(x?.subtitle||'')}"></label><label class="field full">图片 URL<input id="pImage" value="${esc(x?.image||'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800')}"></label><label class="field full">商品描述<textarea id="pDescription" rows="3">${esc(x?.description||'')}</textarea></label><label class="field">标签<input id="pBadge" value="${esc(x?.badge||'')}"></label><label class="field">销量<input id="pSales" type="number" min="0" value="${x?.sales||0}"></label><label class="field">状态<select id="pEnabled"><option value="true" ${x?.enabled!==false?'selected':''}>在售</option><option value="false" ${x?.enabled===false?'selected':''}>下架</option></select></label>${x?'':`<div class="sku-list"><b>初始 SKU</b><div class="sku-row"><input id="skuSpec" placeholder="规格，如：标准版"><input id="skuPrice" type="number" placeholder="售价（元）"><input id="skuStock" type="number" placeholder="库存"><span></span></div></div>`}<div class="form-actions"><button class="secondary" type="button" onclick="closeModal()">取消</button><button class="primary" type="button" onclick="saveProduct('${x?.id||''}')">保存</button></div></div>`)};
window.saveProduct=async id=>{try{const body={categoryId:$('#pCategory').value,name:$('#pName').value.trim(),subtitle:$('#pSubtitle').value.trim(),description:$('#pDescription').value.trim(),image:$('#pImage').value.trim(),badge:$('#pBadge').value.trim()||null,sales:Number($('#pSales').value),enabled:$('#pEnabled').value==='true'};if(!id)body.skus=[{specification:$('#skuSpec').value.trim(),priceCents:Math.round(Number($('#skuPrice').value)*100),originalPriceCents:null,stock:Number($('#skuStock').value),enabled:true}];await api(id?`/products/${id}`:'/products',{method:id?'PATCH':'POST',body:JSON.stringify(body)});closeModal();toast('商品已保存');render()}catch(e){toast(e.message,true)}};
window.skuModal=x=>openModal(`${esc(x.name)} · SKU`, `<div class="form-grid full">${x.skus.map(s=>`<div class="sku-row full"><input id="spec-${s.id}" value="${esc(s.specification)}"><input id="price-${s.id}" type="number" step="0.01" value="${s.priceCents/100}"><input id="stock-${s.id}" type="number" value="${s.stock}"><button class="primary" type="button" onclick="saveSku('${s.id}')">保存</button></div>`).join('')}</div>`);
window.saveSku=async id=>{try{await api(`/skus/${id}`,{method:'PATCH',body:JSON.stringify({specification:$(`#spec-${id}`).value,priceCents:Math.round(Number($(`#price-${id}`).value)*100),stock:Number($(`#stock-${id}`).value)})});toast('SKU 已更新');closeModal();render()}catch(e){toast(e.message,true)}};
async function ordersPage(){const status=$('#orderStatus')?.value||'',orderNo=$('#orderNo')?.value||'',query=`/orders?page=${state.pageNo}&pageSize=15&orderNo=${encodeURIComponent(orderNo)}${status?`&status=${status}`:''}`,d=await api(query);$('#content').innerHTML=`<div class="panel"><div class="toolbar"><div class="filters"><input id="orderNo" placeholder="订单号" value="${esc(orderNo)}"><select id="orderStatus"><option value="">全部状态</option>${Object.entries(statusText).map(([k,v])=>`<option value="${k}" ${status===k?'selected':''}>${v}</option>`).join('')}</select><button class="secondary" onclick="state.pageNo=1;render()">筛选</button></div></div><div class="table-wrap"><table><thead><tr><th>订单号</th><th>用户</th><th>商品</th><th>金额</th><th>状态</th><th>下单时间</th><th>操作</th></tr></thead><tbody>${d.items.map(x=>`<tr><td><b>${esc(x.orderNo)}</b></td><td>${esc(x.nickname||'未命名用户')}</td><td>${esc(x.firstProductName||'—')}<div class="muted">共 ${x.itemCount} 件</div></td><td>${money(x.payableCents)}</td><td><span class="badge ${x.status==='CANCELLED'?'off':x.status==='PAID'?'warn':''}">${statusText[x.status]||x.status}</span></td><td>${date(x.createdAt)}</td><td class="actions"><button onclick="orderDetail('${x.id}')">详情</button>${x.status==='PAID'?`<button onclick="shipModal('${x.id}')">发货</button>`:''}</td></tr>`).join('')}</tbody></table></div>${pager(d)}</div>`}
window.orderDetail=async id=>{try{const x=await api(`/orders/${id}`);openModal(`订单 ${esc(x.orderNo)}`,`<div class="form-grid"><div><span class="muted">状态</span><p>${statusText[x.status]}</p></div><div><span class="muted">实付</span><p>${money(x.payableCents)}</p></div><div class="full"><span class="muted">收货地址</span><p>${esc(Object.values(x.address||{}).filter(Boolean).join(' '))}</p></div><div class="full"><span class="muted">商品明细</span>${x.items.map(i=>`<p>${esc(i.productName)} · ${esc(i.specification)} × ${i.quantity}　${money(i.unitPriceCents)}</p>`).join('')}</div></div>`)}catch(e){toast(e.message,true)}};
window.shipModal=id=>openModal('订单发货',`<div class="form-grid"><label class="field">物流公司<input id="carrier" value="顺丰速运"></label><label class="field">物流单号<input id="tracking" placeholder="至少 4 位"></label><div class="form-actions"><button class="primary" type="button" onclick="ship('${id}')">确认发货</button></div></div>`);
window.ship=async id=>{try{await api(`/orders/${id}/ship`,{method:'POST',body:JSON.stringify({carrier:$('#carrier').value.trim(),trackingNo:$('#tracking').value.trim()})});closeModal();toast('订单已发货');render()}catch(e){toast(e.message,true)}};
async function usersPage(){const keyword=$('#userKeyword')?.value||'',d=await api(`/users?page=${state.pageNo}&pageSize=15&keyword=${encodeURIComponent(keyword)}`);$('#content').innerHTML=`<div class="panel"><div class="toolbar"><div class="filters"><input id="userKeyword" placeholder="昵称或 OpenID" value="${esc(keyword)}"><button class="secondary" onclick="state.pageNo=1;render()">搜索</button></div></div><div class="table-wrap"><table><thead><tr><th>用户</th><th>OpenID</th><th>订单数</th><th>累计消费</th><th>注册时间</th></tr></thead><tbody>${d.items.map(x=>`<tr><td><div class="product-cell">${x.avatarUrl?`<img class="avatar" src="${esc(x.avatarUrl)}">`:'<div class="avatar"></div>'}<b>${esc(x.nickname||'未命名用户')}</b></div></td><td class="muted">${esc(x.openid)}</td><td>${x.orderCount}</td><td>${money(x.spentCents)}</td><td>${date(x.createdAt)}</td></tr>`).join('')}</tbody></table></div>${pager(d)}</div>`}
async function adminsPage(){const items=await api('/super/accounts');state.admins=items;$('#content').innerHTML=`<div class="panel"><div class="toolbar"><div></div><button class="primary" onclick="adminModal()">新增管理员</button></div><div class="table-wrap"><table><thead><tr><th>账号</th><th>显示名</th><th>角色</th><th>状态</th><th>最后登录</th><th>操作</th></tr></thead><tbody>${items.map(x=>`<tr><td><b>${esc(x.username)}</b></td><td>${esc(x.displayName)}</td><td>${x.role==='SUPER_ADMIN'?'超级管理员':'运营管理员'}</td><td><span class="badge ${x.enabled?'':'off'}">${x.enabled?'启用':'停用'}</span></td><td>${date(x.lastLoginAt)}</td><td class="actions"><button onclick="editAdmin('${x.id}')">编辑</button></td></tr>`).join('')}</tbody></table></div></div>`}
window.editAdmin=id=>adminModal(state.admins.find(x=>x.id===id));
window.adminModal=x=>openModal(x?'编辑管理员':'新增管理员',`<div class="form-grid">${x?'':`<label class="field">用户名<input id="aUsername"></label>`}<label class="field">显示名称<input id="aDisplay" value="${esc(x?.displayName||'')}"></label><label class="field">${x?'新密码（留空不改）':'密码（至少 12 位）'}<input id="aPassword" type="password"></label><label class="field">角色<select id="aRole"><option value="OPERATOR" ${x?.role!=='SUPER_ADMIN'?'selected':''}>运营管理员</option><option value="SUPER_ADMIN" ${x?.role==='SUPER_ADMIN'?'selected':''}>超级管理员</option></select></label>${x?`<label class="field">状态<select id="aEnabled"><option value="true" ${x.enabled?'selected':''}>启用</option><option value="false" ${!x.enabled?'selected':''}>停用</option></select></label>`:''}<div class="form-actions"><button class="primary" type="button" onclick="saveAdmin('${x?.id||''}')">保存</button></div></div>`);
window.saveAdmin=async id=>{try{const body={displayName:$('#aDisplay').value.trim(),role:$('#aRole').value};const password=$('#aPassword').value;if(password)body.password=password;if(id)body.enabled=$('#aEnabled').value==='true';else{body.username=$('#aUsername').value.trim();body.password=password}await api(id?`/super/accounts/${id}`:'/super/accounts',{method:id?'PATCH':'POST',body:JSON.stringify(body)});closeModal();toast('管理员已保存');render()}catch(e){toast(e.message,true)}};
async function auditPage(){const items=await api(`/super/audit-logs?page=${state.pageNo}&pageSize=20`);$('#content').innerHTML=`<div class="panel"><div class="table-wrap"><table><thead><tr><th>时间</th><th>管理员</th><th>动作</th><th>资源</th><th>IP</th><th>详情</th></tr></thead><tbody>${items.map(x=>`<tr><td>${date(x.createdAt)}</td><td>${esc(x.username||'系统')}</td><td><span class="badge">${esc(x.action)}</span></td><td>${esc(x.resourceType)}<div class="muted">${esc(x.resourceId||'')}</div></td><td>${esc(x.ipAddress||'—')}</td><td class="muted">${esc(JSON.stringify(x.details))}</td></tr>`).join('')}</tbody></table></div><div class="pagination"><button class="secondary" onclick="prevPage()" ${state.pageNo===1?'disabled':''}>上一页</button><span>第 ${state.pageNo} 页</span><button class="secondary" onclick="nextPage()" ${items.length<20?'disabled':''}>下一页</button></div></div>`}
function pager(d){return `<div class="pagination"><button class="secondary" onclick="prevPage()" ${d.page<=1?'disabled':''}>上一页</button><span>第 ${d.page} 页，共 ${d.total} 条</span><button class="secondary" onclick="nextPage()" ${d.page*d.pageSize>=d.total?'disabled':''}>下一页</button></div>`}window.prevPage=()=>{state.pageNo--;render()};window.nextPage=()=>{state.pageNo++;render()};
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').showModal()}window.closeModal=()=>$('#modal').close();
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({username:$('#username').value.trim(),password:$('#password').value})});state.token=d.accessToken;state.admin=d.admin;sessionStorage.setItem('adminToken',state.token);sessionStorage.setItem('adminUser',JSON.stringify(state.admin));showApp()}catch(err){$('#loginError').textContent=err.message}});
$('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(b)navigate(b.dataset.page)});$('#logoutBtn').onclick=logout;$('#refreshBtn').onclick=render;showApp();
